baseURL = "http://www.michelrealestate.lu"
languageCode = "en-us"
title = "Michel Real Estate | Luxembourg"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1

[[menu.main]]
name    = "Services"
url     = "service"
weight  = 2

[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 3

[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 4

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io



# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "HI, MY NAME IS MICHEL & I AM A"
description = "Convincing your potential buyers or renters to go with your property is what me and my team do best. Our marketing strategy has proven to be one of the country's most successful." 

# button
btn     = true
btnText = "CONTACT ME"
btnURL  = "/contact"

# flip text
[[params.banner.flipText]]
title   = "REAL ESTATE AGENT"
[[params.banner.flipText]]
title   = "CONSULTANT"
[[params.banner.flipText]]
title   = "INVESTOR"
[[params.banner.flipText]]
title   = "FATHER"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "As an investor myself, I can relate to any property owner’s fears and needs. Trust me I have been in your shoes and have seen the worst. Most agents are just agents and want to catch that commission check as fast as possible. My team implements a tailor-made approach and strives to bring results, not empty promisses. Your success is our success, it’s as simple as that."
image   = "images/about/about.png"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "It’s my job to be your expert when it comes to selling or renting your property."
btnText = "New Listings"
btnURL  = "https://www.immotop.lu/estate-agency/michel-real-estate-d42316/index1.html"


# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/Michel.Kmiotek/"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/michelkmiotek/"

[[params.socialIcon]]
icon = "ion-home"
url = "https://www.immotop.lu/estate-agency/michel-real-estate-d42316/index1.html"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/KmiotekMichel"

[[params.socialIcon]]
icon = "ion-play"
url = "https://www.youtube.com/channel/UCtiB6apwM4CaGiILUm25xSA"
